### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by nmder** [moritzgloeckl/overleaf-sync#1]
Hello,

I was not able to login using the following:
`ols login`
and
`ols login -u <username> -p <password>`

Got this message:
`Error: Login failed. Check username and/or password.`

Thank you!

**Comment by moritzgloeckl** [comment]
There seems to be an issue in how the login works. I will take a look.

**Comment by nmder** [comment]
I think I found an issue.
"overleaf_session" is now "overleaf_session2" in [https://github.com/moritzgloeckl/overleaf-sync/blob/5d104f65c72b5ba8120c79d687388a7276f98c41/olsync/olclient.py#L52].

**Comment by nmder** [comment]
Yes. That was the issue. I can login and sync now.
Thank you!

**Comment by moritzgloeckl** [comment]
Great, I will release a fix!

**Comment by moritzgloeckl** [comment]
New version is published, please run `pip3 install --upgrade overleaf-sync` to upgrade :)
