### ISSUE TITLE
Issues when attempting to sync only subfolders

### ISSUE THREAD

**Issue by TesaryLin** [moritzgloeckl/overleaf-sync#18]
Hello,

Is it possible to sync the local folder with a different name than the one on Overleaf? Currently my local project folders have the following structure: "project-A/Code", ""project-A/Data", "project-A/Draft". I'd like to sync only contents in "project-A/Draft" to Overleaf's "project-A". 

I am trying to specify the subfolder directory when typing in the command: `ols -l -p Draft`. But it returns the following error: 

```
No such file or directory: 'Draft/Draft/[filename]'
```

Am I using the directory option incorrectly?

**Comment by moritzgloeckl** [comment]
Hi @TesaryLin,

I've merged some PRs, so you should now be able to specify the Overleaf project name through "-n/--name"

**Comment by TesaryLin** [comment]
Thank you @moritzgloeckl ! Now it works like a charm.
