### ISSUE TITLE
About the usefulness of the project

### ISSUE THREAD

**Issue by twangnh** [moritzgloeckl/overleaf-sync#21]
Hi @moritzgloeckl  thanks for sharing the project, I'm wondering what is the advantage of this project, compared to directly copy and past whole file to overleaf ?

**Comment by twangnh** [comment]
is it easy to sync all kinds of files like figures, bib, etc?

**Comment by moritzgloeckl** [comment]
Hi @twangnh

This project allows you to easily sync all files from and to your Overleaf project. It is smart enough to notice which files have been changed. It basically does copy and paste the file, whoever it does this in a more easy, faster and secure (overwriting) way. It's possible to sync all files.

Why not try it out on a sample project and see if it works for you?

Cheers
Moritz
