### ISSUE TITLE
Login works, project query doesn't: "Error: Project could not be queried."

### ISSUE THREAD

**Issue by MatthiasvB** [moritzgloeckl/overleaf-sync#23]
So I've been using this tool for a couple of weeks now to sync my thesis to overleaf. Worked like a charm, thanks for that!
Every once in a while, I would get the error mentioned in the title. Then I would remove the `.olauth` cookie and `ols login` newly. Then it would work again, usually for for a couple of days, or at least that day. Now, since yesterday, I'm facing the issue that I can login, but `ols` or `ols -l` always immediately gives the error 

>Error: Project could not be queried.

So I'm not able to sync at all...

**Comment by phymann** [comment]
I encounter the same problem.

**Comment by clagger** [comment]
Same problem here!
Obviously Overleaf changed something on their site?

**Comment by tiri** [comment]
I also encountered this problem today. When I got to the bottom of the cause, I found that Overleaf had changed their page structure. So I quickly created a pull request with a possible solution.

**Comment by moritzgloeckl** [comment]
I will take a look, thank you for opening this issue. They seem to be changing these kind of things every now and then which breaks the ols workflow.

**Comment by moritzgloeckl** [comment]
Should be fixed now, please update `ols` to version `1.1.3` and try again :)
