### ISSUE TITLE
ignoring files mechanism like `.gitignore`

### ISSUE THREAD

**Issue by zeyutang** [moritzgloeckl/overleaf-sync#3]
As titled, just wondering if there is something like `.gitignore` one can make use of.
Thank you!

**Comment by moritzgloeckl** [comment]
Cool idea! What would you suggest, or how would you expect it to work? Do you think it makes sense to specify it every time using the command (like: `--ignore ".gitignore"`)? Or have the ignore files in a specific file (like: `.ol-ignore`)? Or something else?

Open for your suggestions. Thanks.

**Comment by zeyutang** [comment]
Yeah, just like `.gitignore`.
I implemented a version. The command is like `--olignore ".olignore"`. Already submitted a pull request.
Thank you!

**Comment by moritzgloeckl** [comment]
Thanks again for your help, I released a new version on PyPI :)
