### ISSUE TITLE
encounter error after update to version 1.1.5

### ISSUE THREAD

**Issue by phymann** [moritzgloeckl/overleaf-sync#30]
Hi all,

After install the newest version, i.e., version 1.1.5, when run `ols --version`, I encounter the following error:
```
Traceback (most recent call last):
  File "/home/jw-ub-pc/.local/bin/ols", line 5, in <module>
    from olsync.olsync import main
  File "/home/jw-ub-pc/.local/lib/python3.8/site-packages/olsync/olsync.py", line 48, in <module>
    def main(ctx, local, remote, project_name, cookie_path, sync_path, olignore_path, verbose):
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 282, in decorator
    return option(*(param_decls or ('--version',)), **attrs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1547, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

Similarly error also occurs on Mac, how to fix this?

Best,
JW

**Comment by moritzgloeckl** [comment]
Hi,

I've noticed this issue as well but it shouldn't mess with the syncing. This is just related to the version option. Can you please reinstall overleaf-sync and check again?

Thanks.

**Comment by phymann** [comment]
> Hi,
> 
> I've noticed this issue as well but it shouldn't mess with the syncing. This is just related to the version option. Can you please reinstall overleaf-sync and check again?
> 
> Thanks.

I've tried uninstall and install again. Still encounter the same error...

**Comment by phit0** [comment]
Hi, I encountered exactly the same error using Ubuntu 20.4 and python 3.8.

**Comment by zzjjzzgggg** [comment]
a quick fix:

In the file `~/.local/lib/python3.8/site-packages/olsync/olsync.py`, just commet out line 48: `@click.version_option(package_name='overleaf-sync')`.

**Comment by phymann** [comment]
> a quick fix:
> 
> In the file `~/.local/lib/python3.8/site-packages/olsync/olsync.py`, just commet out line 48: `@click.version_option(package_name='overleaf-sync')`.

Thank you, it indeed works!
