### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by matifali** [moritzgloeckl/overleaf-sync#44]
When I try to log in using the command `ols login`, I get this error.

```
Gtk-Message: 02:46:58.768: Failed to load module "xapp-gtk3-module"
Gtk-Message: 02:46:58.768: Failed to load module "xapp-gtk3-module"
Error: Login failed. Please try again.
```

Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy

**Comment by matifali** [comment]
I installed the following dependencies and the error is gone but now I do not see any window to login.
`python-xapp`
`libxapp-dev`
`gir1.2-xapp-1.0`
`xapps-common`
`libxapp1`

**Comment by moritzgloeckl** [comment]
Maybe this will be fixed with the new Qt library we will introduce. I will close this issue as the problem is probably not with `ols` but with the Qt dependencies on your OS...
