### ISSUE TITLE
Clarify how `.olignore` works

### ISSUE THREAD

**Issue by multimeric** [moritzgloeckl/overleaf-sync#45]
So I setup my `.olignore` like I would a `.gitignore`, but I noticed that it wasn't working the same. For example my `.olignore` just had the path `out` in it, but this didn't result in any of the `out/foo.aux` files being ignored.

So, having a look at the source code, I found:
https://github.com/moritzgloeckl/overleaf-sync/blob/0a6039713128a4a1f942c84336a90c54db4adae9/olsync/olsync.py#L275-L276

So it uses [`fnmatch`](https://docs.python.org/3/library/fnmatch.html) patterns, which aren't the same as `.gitignore` patterns. Any future users note that you will have to use globs like `out/*` to match directories instead of just `out`.

I think it would be good if this could be updated in the docs and also the CLI help.

**Comment by moritzgloeckl** [comment]
Thank you, I will update the readme accordingly.
