### ISSUE TITLE
Login window keeps blank

### ISSUE THREAD

**Issue by jcvillaquira** [moritzgloeckl/overleaf-sync#46]
When running

`ols login --path /path/to/file`

a window is open. However, it just stays blank and nothing happens. I am using Manjaro i3. After a while I get the following output:

```bash
⠧ Login[1011:1027:0518/234710.240508:ERROR:quic_idle_network_detector.cc(102)] SetAlarm called after stopped

⠴ Loginlibpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

⠹ Login
```

**Comment by TahsinTariq** [comment]
Same issue on PopOS 22.04. The new window stays blank.

It works fine on PopOS 21.10 though.

**Comment by moritzgloeckl** [comment]
Some weird issue with Qt and PopOS I guess. I think I cannot really help here as I don't know what's going on... Try opening an issues on the Qt project.

Soon I will provide an updated version with PySide6 (updated library) maybe that'll fix your issue!
