### ISSUE TITLE
sub-directory files syncing

### ISSUE THREAD

**Issue by zeyutang** [moritzgloeckl/overleaf-sync#5]
It seems that currently the package does not support syncing for sub-directory files yet.
For example, if I have a projct like this:
project-root
  |-- sections
  |      |--sec1.tex
  |      |--sec2.tex
  |--main.tex
  |--style.sty

Only `main.tex` and `style.sty` will be synced.

**Comment by moritzgloeckl** [comment]
Fixed with #4
