### ISSUE TITLE
Download compiled project pdfs

### ISSUE THREAD

**Issue by sandeepnmenon** [moritzgloeckl/overleaf-sync#51]
**Feature request**
API to download compiled project pdf file.

**Comment by moritzgloeckl** [comment]
Can you please give some more info on how you would like this to work. How would you use this feature?

**Comment by sandeepnmenon** [comment]
Essentially, when I make some changes in overleaf, I always have to use the recompile button and then download the pdf, to update it in my servers.
Instead, I should be able to just make the changes and have my script run, which would download the new pdf and upload it in multiple places.

**Comment by moritzgloeckl** [comment]
You can of course always locally compile it as well with your files.

Will check how easy this is to implement

**Comment by moritzgloeckl** [comment]
Good news @sandeepnmenon I just published version 1.2.0 where this is implemented 🎉 Please update to this version and test the feature 😉

**Comment by sandeepnmenon** [comment]
That's great! Thank you @moritzgloeckl 
I'll start building my automated pipelines with this.
