### ISSUE TITLE
.olignore not work for folders

### ISSUE THREAD

**Issue by Lightup1** [moritzgloeckl/overleaf-sync#52]
.olignore not work for folders as .gitignore
For example, you have a folder `test` with some file in it.
Then you add `test` to .olignore, `ols -l` command will also upload the folder test and the files in it.

**Comment by moritzgloeckl** [comment]
Unfortunately there was a mistake in the documentation - `.olignore` does not work like a `.gitignore`. Please see issue #45 and https://docs.python.org/3/library/fnmatch.html for more information.

If you want to exclude the folder `test` you need to put `test/*` in `.olignore`.
