### ISSUE TITLE
Cannot do any queries

### ISSUE THREAD

**Issue by SGoerzen** [moritzgloeckl/overleaf-sync#69]
I am not able to query all projects (list, download, sync). Login did work.

I am using Windows 11 and Python 3.10.5

![grafik](https://user-images.githubusercontent.com/17460000/232767139-bbe21d70-fee3-460b-bb25-9d5a6e9b38bb.png)

Do you have an idea?

**Comment by mone27** [comment]
hey @SGoerzen can you run the command with the `-v` option to see where is the error.

you should run: `ols -v`
