### ISSUE TITLE
FYI: Free overleaf account can use 'git'

### ISSUE THREAD

**Issue by pchampio** [moritzgloeckl/overleaf-sync#8]
Under the `sync/git` tab, overleaf provides a git url to pull/push to the project.

Example:
```
git clone https://git.overleaf.com/__ID__ myproject
git add readme.md
git push
```
it behaves exactly like git.

**Comment by pchampio** [comment]
Not really a issue, just a notice. Closing this issue.

**Comment by moritzgloeckl** [comment]
I don't think it's actually free, see https://www.overleaf.com/learn/how-to/How_do_I_push_a_new_project_to_Overleaf_via_git%3F
